### PR TITLE
Update vendors.json

### PR DESCRIPTION
**Pull request by priyamsodhiya**
Add Zenskar to Billing vendors

### CODE REVIEW

**Review by Rishabhkaul — APPROVED** [review]

**Comment by priyamsodhiya** [comment]
Thanks @Rishabhkaul for approving the changes, however the changes don't reflect on the webpage (https://www.usagebased.org/) Is there reason for that?

**Comment by priyamsodhiya** [comment]
@Rishabhkaul Just following up once again to check if there is anything I should to make the changes reflect on the live website. Sorry for the trouble but this is important for me.

**Comment by priyamsodhiya** [comment]
Hi @Rishabhkaul Please let me know if there is anything I need to add Zenskar (Zenskar.com) to the list of vendots

**Comment by priyamsodhiya** [comment]
@Rishabhkaul, just checking in once again if there is anything else I need to do to add Zenskar (Zenskar.com) to the list of vendors

**Pull request merged**
